import {mkdir,rm,cp,writeFile} from 'node:fs/promises';
import {renderPage,routes} from '../src/components.js';
import {translator} from '../src/content.js';
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});await cp('src','dist/src',{recursive:true});
const t=translator('en');
const netlifyForm=`<form name="website-request" method="POST" data-netlify="true" netlify-honeypot="company-url" hidden enctype="multipart/form-data"><input name="form-name" value="website-request"><input name="company-url"><input name="name"><input name="email"><textarea name="request"></textarea>${Array.from({length:20},(_,i)=>`<input type="file" name="attachment-${i}">`).join('')}</form>`;
for(const route of routes){const title=t('nav').split('|')[routes.indexOf(route)];const html=`<!doctype html><html lang="en" data-form-backend="${process.env.NETLIFY==='true'?'netlify':'download'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#087af0"><meta name="description" content="${route==='complex-sites'?t('complexIntro'):t('intro')}"><title>${title} · I Build Cheap Simple Websites Fast</title><link rel="icon" type="image/webp" href="/assets/logo.webp"><link rel="stylesheet" href="/src/styles.css"><script type="module" src="/src/app.js"></script></head><body>${route==='apply'?'<noscript><p class="container notice">Please enable JavaScript to use the website request form.</p></noscript>':''}<div id="app">${renderPage(route,'en')}</div>${route==='apply'?netlifyForm:''}</body></html>`;const dir=`dist/${route}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}/index.html`,html)}
await writeFile('dist/404.html','<!doctype html><html lang="en"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found</title><link rel="stylesheet" href="/src/styles.css"><main class="container page-hero"><h1>404</h1><p>Page not found / Seite nicht gefunden / Stranica nije pronađena</p><a class="button" href="/">Home / Startseite / Početna →</a></main></html>');
console.log('Built four static pages in dist/.');
