// Each key contains [English, German, Croatian]. Keep the order consistent.
export const languages = ['en', 'de', 'hr'];
export const palettes = [
 ['#071A2B','#1687F8','#25B63A','#FFA000'],
 ['#233D4D','#619B8A','#A1C181','#F4F1DE'],
 ['#352F44','#776B9E','#B9A7D0','#F4EFF8'],
 ['#432818','#99582A','#DDA15E','#FFF3DF'],
 ['#183153','#347AB7','#83C5BE','#EDF6F9'],
 ['#292524','#78716C','#D6D3D1','#FAFAF9']
];
export const copy = {
duckReference: ['Reference: Custom CRM system','Referenz: Individuelles CRM-System','Referenca: Prilagođeni CRM sustav'],
customCrmTitle: ['Custom CRM system','Individuelles CRM-System','Prilagođeni CRM sustav'],
colorPickerHint: ['Click the colour to open the colour picker.','Klicke auf die Farbe, um die Farbauswahl zu öffnen.','Klikni boju za otvaranje birača boja.'],
referenceUrl: ['Reference website URL','URL der Referenz-Website','URL referentne stranice'],
addReferenceUrl: ['Add reference website','Referenz-Website hinzufügen','Dodaj referentnu stranicu'],
effectsTitle: ['Effects & movement (optional)','Effekte & Bewegung (optional)','Efekti i animacije (opcionalno)'],
effectsIntro: ['Click an effect to preview it below. Tick the + beside any effects you want on your website. You can choose several.','Klicke auf einen Effekt, um ihn unten zu testen. Markiere das + neben den gewünschten Effekten. Du kannst mehrere wählen.','Klikni efekt za pregled ispod. Označi + uz efekte koje želiš na svojoj stranici. Možeš odabrati više njih.'],
effectInclude: ['Include this effect','Diesen Effekt auswählen','Uključi ovaj efekt'],
effectReplay: ['Replay','Erneut abspielen','Ponovi'],
effectTry: ['Hover, focus or tap the card to try again. This preview demonstrates one effect at a time.','Bewege den Zeiger über die Karte, fokussiere sie oder tippe darauf, um den Effekt erneut zu testen. Die Vorschau zeigt jeweils einen Effekt.','Prijeđi pokazivačem, fokusiraj ili dodirni karticu za ponovni prikaz. Pregled prikazuje jedan efekt odjednom.'],
effectSample: ['Your website','Deine Website','Tvoja stranica'],
effectSampleHint: ['Try it here','Hier ausprobieren','Isprobaj ovdje'],
effectNone: ['No effects selected — a static design is fine, too.','Keine Effekte ausgewählt — ein statisches Design ist auch möglich.','Nema odabranih efekata — i statičan dizajn je u redu.'],
effectSelected: ['Selected effects','Ausgewählte Effekte','Odabrani efekti'],
effectReduced: ['Your device requests reduced motion, so animated previews are disabled. You can still select effects.','Dein Gerät fordert reduzierte Bewegung an. Animierte Vorschauen sind deshalb deaktiviert. Du kannst weiterhin Effekte auswählen.','Tvoj uređaj traži smanjeno kretanje pa su animirani pregledi isključeni. I dalje možeš odabrati efekte.'],
pageTemplatesTitle: ['Add a page from a template','Seite aus einer Vorlage hinzufügen','Dodaj stranicu iz predloška'],
pageTemplatesHint: ['Choose a page to add editable prompts. Replace the bracketed notes with your own information.','Wähle eine Seite mit bearbeitbaren Hinweisen. Ersetze die Angaben in Klammern durch deine Informationen.','Odaberi stranicu s uputama koje možeš urediti. Zamijeni bilješke u zagradama svojim podacima.'],
legalTemplateHint: ['These prompts collect your information; they are not a finished legal notice or privacy policy.','Diese Hinweise sammeln deine Angaben; sie sind kein fertiges Impressum und keine fertige Datenschutzerklärung.','Ove upute prikupljaju tvoje podatke; nisu gotovi pravni podaci ni politika privatnosti.'],
colorDescription: ['Colour description (optional)','Farbbeschreibung (optional)','Opis boja (opcionalno)'],
paletteNames: ['Bright & playful|Natural & calm|Soft lavender|Warm earth|Fresh ocean|Neutral & minimal','Bunt & lebendig|Natürlich & ruhig|Sanftes Lavendel|Warme Erdtöne|Frischer Ozean|Neutral & minimal','Vedro i razigrano|Prirodno i mirno|Nježna lavanda|Topli zemljani tonovi|Svježi ocean|Neutralno i minimalno'],
paletteHint: ['Choose a palette, then adjust its colours if you like. Selecting another palette replaces the current colours.','Wähle eine Palette und passe ihre Farben bei Bedarf an. Eine andere Palette ersetzt die aktuellen Farben.','Odaberi paletu i prilagodi boje po želji. Odabir druge palete zamjenjuje trenutačne boje.'],
addImageUrl: ['Add image URL','Bild-URL hinzufügen','Dodaj URL slike'],
imageUrl: ['Image URL','Bild-URL','URL slike'],
freeTag: ['FREE','KOSTENLOS','BESPLATNO'],
chooseLanguage: ['Choose language','Sprache wählen','Odaberi jezik'],
nav: ['Simple Sites|Complex Sites|Apply|Contact','Einfache Websites|Komplexe Websites|Anfragen|Kontakt','Jednostavne stranice|Složene stranice|Pošalji upit|Kontakt'],
tagline: ['Simple websites. Clear prices. Fast delivery.','Einfache Websites. Klare Preise. Schnell fertig.','Jednostavne stranice. Jasne cijene. Brza izrada.'],
skip: ['Skip to content','Zum Inhalt springen','Preskoči na sadržaj'],
menu: ['Open navigation','Navigation öffnen','Otvori navigaciju'],
hero: ['Simple website.','Einfache Website.','Jednostavna web stranica.'],
heroPrice: ['€80. In 7 days.','80 €. In 7 Tagen.','80 €. Za 7 dana.'],
intro: ['Your idea deserves a place on the internet. A simple website without agency prices, complicated contracts or monthly website-builder subscriptions.','Deine Idee verdient einen Platz im Internet. Eine einfache Website ohne Agenturpreise, komplizierte Verträge oder monatliche Baukasten-Abos.','Tvoja ideja zaslužuje mjesto na internetu. Jednostavna stranica bez agencijskih cijena, kompliciranih ugovora ili mjesečnih pretplata na alate za izradu stranica.'],
start: ['Start your website','Starte deine Website','Pokreni svoju stranicu'],
howLink: ['See how it works','So funktioniert’s','Kako funkcionira'],
previewFirst: ['Preview first. Pay only if you like it.','Erst ansehen. Nur zahlen, wenn es dir gefällt.','Prvo pregledaj. Plati ako ti se sviđa.'],
heroNote: ['Made for your next small, big thing.','Für deine nächste kleine, große Idee.','Za tvoju sljedeću malu, veliku ideju.'],
benefits: ['€80 fixed price|Preview in 3 working days|3 correction rounds|Up to 2 languages','80 € Festpreis|Vorschau in 3 Werktagen|3 Korrekturrunden|Bis zu 2 Sprachen','Fiksna cijena 80 €|Pregled za 3 radna dana|3 kruga izmjena|Do 2 jezika'],
howTitle: ['Very simple steps:','Ganz einfache Schritte:','Vrlo jednostavni koraci:'],
steps: ['You tell me what you need|Preview in 3 working days|Like it? Confirm for €80|3 corrections included','Du sagst mir, was du brauchst|Vorschau in 3 Werktagen|Gefällt sie dir? Für 80 € bestätigen|3 Korrekturrunden inklusive','Reci mi što trebaš|Pregled za 3 radna dana|Sviđa ti se? Potvrdi za 80 €|Uključena 3 kruga izmjena'],
freeAddress: ['A free Netlify address is included:','Eine kostenlose Netlify-Adresse ist inklusive:','Uključena je besplatna Netlify adresa:'],
workTitle: ['Reference websites','Referenz-Websites','Referentne web stranice'],
visit: ['Visit website','Website besuchen','Posjeti stranicu'],
placeholder: ['Preview placeholder','Platzhalter für Vorschau','Mjesto za pregled'],
priceLabel: ['ONE SIMPLE PACKAGE','EIN EINFACHES PAKET','JEDNOSTAVAN PAKET'],
priceTitle: ['Your website. Ready in 7 days.','Deine Website. Fertig in 7 Tagen.','Tvoja stranica. Gotova za 7 dana.'],
priceDetail: ['Preview within 3 working days · 3 correction rounds included','Vorschau in 3 Werktagen · 3 Korrekturrunden inklusive','Pregled za 3 radna dana · Uključena 3 kruga izmjena'],
oneTime: ['one-time payment','einmalige Zahlung','jednokratno'],
addons: ['You want your own domain?','Du willst deine eigene Domain?','Želiš vlastitu domenu?'],
addonsAccent: ['No prob!','Kein Problem!','Nema problema!'],
addonLabel: ['Add-ons','Extras','Dodaci'],
domainTitle: ['Use your own .com / .de / .hr domain','Nutze deine eigene .com / .de / .hr Domain','Koristi svoju .com / .de / .hr domenu'],
domainCost: ['€30 setup. Domain usually €5–€20 per year, depending on the domain.','30 € Einrichtung. Die Domain kostet je nach Domain meist 5–20 € pro Jahr.','30 € za postavljanje. Domena obično košta 5–20 € godišnje, ovisno o domeni.'],
domainLink: ['Check domain prices on STRATO','Domainpreise bei STRATO prüfen','Provjeri cijene domena na STRATO-u'],
complexPromo: ['Need something more powerful?','Brauchst du mehr Funktionen?','Trebaš nešto naprednije?'],
complexPromoText: ['Booking systems, a CRM, user accounts or online payments? Let’s build something that does the heavy lifting for you.','Buchungssystem, CRM, Benutzerkonten oder Online-Zahlungen? Lass uns etwas bauen, das dir Arbeit abnimmt.','Rezervacije, CRM, korisnički računi ili online plaćanja? Izradimo nešto što preuzima dio posla.'],
seeComplex: ['Explore complex websites','Komplexe Websites ansehen','Pogledaj složene stranice'],
complexTitle: ['Return of investment in a year','Amortisation innerhalb eines Jahres','Povrat ulaganja u godinu dana'],
complexIntro: ['For websites that need more than a few static pages. Custom tools that turn everyday admin into time for something better.','Für Websites, die mehr als statische Seiten brauchen. Individuelle Werkzeuge, die dir im Alltag Zeit sparen.','Za stranice kojima treba više od nekoliko statičnih stranica. Prilagođeni alati koji štede vrijeme u svakodnevnom poslu.'],
features: ['Booking systems|CRM systems|Calendars|User accounts & login|Online payments|Databases|Admin dashboards|Custom forms|Dynamic content','Buchungssysteme|CRM-Systeme|Kalender|Benutzerkonten & Login|Online-Zahlungen|Datenbanken|Admin-Dashboards|Individuelle Formulare|Dynamische Inhalte','Sustavi rezervacija|CRM sustavi|Kalendari|Korisnički računi i prijava|Online plaćanja|Baze podataka|Administratorske ploče|Prilagođeni obrasci|Dinamičan sadržaj'],
development: ['Development','Entwicklung','Izrada'],
quoteDetail: ['The exact price depends on the features and complexity of your website.','Der genaue Preis hängt vom Funktionsumfang und der Komplexität deiner Website ab.','Točna cijena ovisi o funkcijama i složenosti tvoje stranice.'],
describe: ['Describe your project','Beschreibe dein Projekt','Opiši svoj projekt'],
ongoing: ['Clear about the ongoing costs, too.','Auch die laufenden Kosten sind transparent.','Jasni su i tekući troškovi.'],
costNames: ['Hosting|Domain|General maintenance (debugging)|Text or image changes|Feature additions','Hosting|Domain|Allgemeine Wartung (Fehlerbehebung)|Text- oder Bildänderungen|Neue Funktionen','Hosting|Domena|Opće održavanje (ispravljanje grešaka)|Izmjene teksta ili slika|Nove funkcije'],
costValues: ['€5–€10 / month|€5–€20 / year|€10 / month|€10 per request|Quoted individually','5–10 € / Monat|5–20 € / Jahr|10 € / Monat|10 € pro Anfrage|Individuelles Angebot','5–10 € / mjesečno|5–20 € / godišnje|10 € / mjesečno|10 € po zahtjevu|Individualna ponuda'],
costNote: ['Estimates, not a fixed quote. Hosting depends on traffic and technical requirements. Domain prices vary.','Richtwerte, kein Festangebot. Hosting hängt von Traffic und technischen Anforderungen ab. Domainpreise variieren.','Procjene, a ne fiksna ponuda. Hosting ovisi o prometu i tehničkim zahtjevima. Cijene domena variraju.'],
builderTitle: ['Why not just use Wix or Squarespace?','Warum nicht einfach Wix oder Squarespace?','Zašto ne koristiti Wix ili Squarespace?'],
builderText: ['Website builders have their place. As an illustrative example, a plan with business features and extra services could total €50/month. Actual prices depend on the provider, plan and features.','Website-Baukästen haben ihre Vorteile. Als Rechenbeispiel könnten ein Tarif mit Geschäftsfunktionen und Zusatzdiensten insgesamt 50 €/Monat kosten. Tatsächliche Preise hängen von Anbieter, Tarif und Funktionen ab.','Alati za izradu stranica imaju svoje prednosti. Kao ilustrativni primjer, paket s poslovnim funkcijama i dodatnim uslugama mogao bi iznositi 50 €/mjesečno. Stvarne cijene ovise o pružatelju, paketu i funkcijama.'],
builderMath: ['€50/month → €600/year → €1,800 over 3 years','50 €/Monat → 600 €/Jahr → 1.800 € in 3 Jahren','50 €/mjesečno → 600 €/godišnje → 1.800 € za 3 godine'],
customMath: ['Custom site: approx. €15–€20/month for hosting + maintenance, plus domain and development. Over 3 years: approx. €1,055–€1,780+ including €500–€1,000+ development. Changes cost extra.','Individuelle Website: ca. 15–20 €/Monat für Hosting + Wartung, dazu Domain und Entwicklung. Über 3 Jahre: ca. 1.055–1.780 €+ inklusive 500–1.000 €+ Entwicklung. Änderungen kosten extra.','Prilagođena stranica: oko 15–20 €/mjesečno za hosting + održavanje, uz domenu i izradu. Za 3 godine: oko 1.055–1.780 €+ uključujući izradu od 500–1.000 €+. Izmjene se dodatno naplaćuju.'],
bookingTitle: ['Example: Calendar & Booking System','Beispiel: Kalender & Buchungssystem','Primjer: Kalendar i rezervacije'],
bookingText: ['A simple journey from finding a service to confirming an appointment. Layout demo; live booking is not enabled.','Ein einfacher Weg von der Leistungsauswahl bis zur Terminbestätigung. Layout-Demo; keine echte Buchung möglich.','Jednostavan put od odabira usluge do potvrde termina. Primjer izgleda; stvarne rezervacije nisu omogućene.'],
bookingSteps: ['Choose a service|Choose a practitioner|Pick a date|Select a time|Booking confirmed','Leistung auswählen|Fachkraft auswählen|Datum wählen|Uhrzeit wählen|Buchung bestätigt','Odaberi uslugu|Odaberi stručnjaka|Odaberi datum|Odaberi vrijeme|Rezervacija potvrđena'],
inspiration: ['Reference: Harmonie Studio','Referenz: Harmonie Studio','Referenca: Harmonie Studio'],
likeThis: ['I need something like this','So etwas brauche ich','Trebam nešto ovakvo'],
crmTitle: ['Example: A CRM that keeps things together.','Beispiel: Ein CRM, das alles zusammenhält.','Primjer: CRM koji sve drži na jednom mjestu.'],
crmText: ['Manage contacts, groups, events, polls and communication in one place. A custom CRM can fit the way your business actually works.','Verwalte Kontakte, Gruppen, Events, Umfragen und Kommunikation an einem Ort. Ein individuelles CRM passt zu deinen Arbeitsabläufen.','Upravljaj kontaktima, grupama, događajima, anketama i komunikacijom na jednom mjestu. Prilagođeni CRM prati način na koji tvoje poslovanje radi.'],
crmLabels: ['Contacts|Groups|Events|Communication|Group overview|Women|Men|Total|Park|Café|Bar|Boulder hall|Available slot','Kontakte|Gruppen|Events|Kommunikation|Gruppenübersicht|Frauen|Männer|Gesamt|Park|Café|Bar|Boulderhalle|Freier Platz','Kontakti|Grupe|Događaji|Komunikacija|Pregled grupa|Žene|Muškarci|Ukupno|Park|Kafić|Bar|Dvorana za penjanje|Slobodno mjesto'],
crmNote: ['Illustrative layout based on the supplied CRM reference. Original screenshot to be added.','Beispiel-Layout auf Basis der CRM-Referenz. Original-Screenshot wird noch ergänzt.','Primjer izgleda prema priloženoj CRM referenci. Izvorna snimka zaslona bit će dodana.'],
moreWork: ['More projects','Weitere Projekte','Ostali projekti'],
applyTitle: ['Tell me about your website.','Erzähl mir von deiner Website.','Reci mi nešto o svojoj stranici.'],
applyIntro: ['The more you share, the closer the first preview will be to what you have in mind. No payment needed to get started.','Je mehr du erzählst, desto näher kommt die erste Vorschau deiner Vorstellung. Zum Start ist keine Zahlung nötig.','Što više podijeliš, to će prvi pregled biti bliži tvojoj zamisli. Za početak nije potrebno plaćanje.'],
contactTitle: ['Let’s talk.','Lass uns reden.','Razgovarajmo.'],
contactIntro: ['Have a question before you apply?','Hast du vor deiner Anfrage noch eine Frage?','Imaš pitanje prije slanja upita?'],
contactPending: ['Contact details are coming soon. You can prepare your website request using the application form.','Kontaktdaten folgen in Kürze. Du kannst deine Website-Anfrage über das Formular vorbereiten.','Kontaktni podaci stižu uskoro. Svoj zahtjev za stranicu možeš pripremiti putem obrasca.'],
comingSoon: ['Coming soon','Folgt in Kürze','Uskoro'],
social: ['Social media','Social Media','Društvene mreže'],
footerNote: ['A little website. A big step forward.','Eine kleine Website. Ein großer Schritt.','Mala stranica. Velik korak naprijed.'],
formSteps: ['Contact|Your project|Style & languages|Assets & pages|Features & finish','Kontakt|Dein Projekt|Stil & Sprachen|Dateien & Seiten|Funktionen & Abschluss','Kontakt|Tvoj projekt|Stil i jezici|Datoteke i stranice|Funkcije i završetak'],
name: ['Name','Name','Ime'], email: ['Email','E-Mail','E-mail'], phone: ['Phone / WhatsApp','Telefon / WhatsApp','Telefon / WhatsApp'],
method: ['Preferred contact method','Bevorzugter Kontaktweg','Željeni način kontakta'], phoneOption: ['Phone','Telefon','Telefon'],
business: ['Business / project name','Name des Unternehmens / Projekts','Naziv tvrtke / projekta'], businessDesc: ['What does your business / project do?','Was macht dein Unternehmen / Projekt?','Čime se bavi tvoja tvrtka / projekt?'],
socialUrls: ['Social media pages (optional)','Social-Media-Seiten (optional)','Društvene mreže (opcionalno)'], currentUrl: ['Current website (optional)','Aktuelle Website (optional)','Trenutna stranica (opcionalno)'],
socialUrl: ['Social media URL','Social-Media-URL','URL društvene mreže'],
addSocialUrl: ['Add social media link','Social-Media-Link hinzufügen','Dodaj poveznicu na društvenu mrežu'],
addWebsiteUrl: ['Add website','Website hinzufügen','Dodaj stranicu'],
siteType: ['What kind of website do you need?','Welche Art von Website brauchst du?','Kakva ti stranica treba?'],
siteOptions: ['Simple €80 website|Complex website|Not sure','Einfache Website für 80 €|Komplexe Website|Noch unsicher','Jednostavna stranica za 80 €|Složena stranica|Nisam siguran/na'],
description: ['General website description','Allgemeine Website-Beschreibung','Opći opis stranice'], refs: ['Reference websites (optional)','Referenz-Websites (optional)','Referentne stranice (opcionalno)'],
likes: ['What do you like about these websites?','Was gefällt dir an diesen Websites?','Što ti se sviđa na tim stranicama?'], dislikes: ['What do you definitely NOT want?','Was möchtest du auf keinen Fall?','Što nikako NE želiš?'],
colors: ['Colours you like','Farben, die dir gefallen','Boje koje ti se sviđaju'], addColor: ['Add colour','Farbe hinzufügen','Dodaj boju'], hex: ['HEX colour','HEX-Farbe','HEX boja'], remove: ['Remove','Entfernen','Ukloni'],
navigation: ['Navigation preference','Gewünschte Navigation','Željena navigacija'], navOptions: ['Top navigation|Side navigation|Not sure','Oben|Seitlich|Noch unsicher','Na vrhu|Sa strane|Nisam siguran/na'],
languageQuestion: ['Which languages should your website support?','Welche Sprachen soll deine Website unterstützen?','Koje jezike treba podržavati tvoja stranica?'], languageOptions: ['English|German|Croatian|Other','Englisch|Deutsch|Kroatisch|Andere','Engleski|Njemački|Hrvatski|Drugi'], otherLang: ['Other languages','Andere Sprachen','Drugi jezici'], langNote: ['The Simple Site package includes up to 2 languages. Each additional language entered counts toward this limit.','Das einfache Paket enthält bis zu 2 Sprachen. Jede zusätzlich eingetragene Sprache zählt zu diesem Limit.','Jednostavni paket uključuje do 2 jezika. Svaki dodatno upisan jezik računa se u to ograničenje.'],
logo: ['Logo upload (optional)','Logo hochladen (optional)','Učitaj logo (opcionalno)'], images: ['Image uploads','Bilder hochladen','Učitaj slike'], imageUrls: ['Image URLs','Bild-URLs','URL-ovi slika'], uploadHint: ['PNG, JPG, WebP or GIF. Up to 20 files, 5 MB per file and 8 MB total.','PNG, JPG, WebP oder GIF. Max. 20 Dateien, 5 MB pro Datei und 8 MB insgesamt.','PNG, JPG, WebP ili GIF. Do 20 datoteka, 5 MB po datoteci i ukupno do 8 MB.'],
pages: ['Your website pages','Deine Website-Seiten','Stranice tvoje web stranice'], addPage: ['Add page','Seite hinzufügen','Dodaj stranicu'], page: ['Page','Seite','Stranica'], home: ['Home','Startseite','Početna'], pageName: ['Page name','Seitenname','Naziv stranice'], pagePurpose: ['Page purpose / description','Zweck / Beschreibung','Svrha / opis stranice'], pageHeadline: ['Page headline','Seitenüberschrift','Naslov stranice'], pageContent: ['Page text / content','Seitentext / Inhalt','Tekst / sadržaj stranice'], instructions: ['Additional instructions','Weitere Hinweise','Dodatne upute'], up: ['Move up','Nach oben','Pomakni gore'], down: ['Move down','Nach unten','Pomakni dolje'],
additional: ['Additional features','Zusätzliche Funktionen','Dodatne funkcije'], additionalOptions: ['Contact form|WhatsApp button|Google Maps|Social media links|Image gallery|Video|Calendar|Booking system|CRM system|Login / accounts|Payments|Database|Newsletter|Other','Kontaktformular|WhatsApp-Button|Google Maps|Social-Media-Links|Bildergalerie|Video|Kalender|Buchungssystem|CRM-System|Login / Konten|Zahlungen|Datenbank|Newsletter|Andere','Kontaktni obrazac|WhatsApp gumb|Google Maps|Poveznice na društvene mreže|Galerija slika|Video|Kalendar|Sustav rezervacija|CRM sustav|Prijava / računi|Plaćanja|Baza podataka|Newsletter|Drugo'],
otherFeatures: ['Other features','Andere Funktionen','Druge funkcije'], complexNotice: ['This will likely require a Complex Website quote rather than the €80 Simple Website package.','Dafür ist voraussichtlich ein Angebot für eine komplexe Website statt des einfachen 80-€-Pakets nötig.','Za ovo će vjerojatno biti potrebna ponuda za složenu stranicu umjesto jednostavnog paketa za 80 €.'],
notes: ['Anything else I should know?','Was sollte ich sonst noch wissen?','Postoji li još nešto što trebam znati?'], agreement: ['I understand that the €80 package is for simple websites and more complex functionality will be quoted separately.','Ich verstehe, dass das 80-€-Paket für einfache Websites gedacht ist und komplexere Funktionen separat angeboten werden.','Razumijem da je paket od 80 € namijenjen jednostavnim stranicama, a složenije funkcije nude se zasebno.'],
next: ['Continue','Weiter','Nastavi'], back: ['Back','Zurück','Natrag'], submit: ['Send website request','Website-Anfrage senden','Pošalji zahtjev'], submitting: ['Sending…','Wird gesendet…','Slanje…'], thanks: ['Thank you. I’ll review your request and contact you.','Vielen Dank. Ich prüfe deine Anfrage und melde mich bei dir.','Hvala. Pregledat ću tvoj zahtjev i javiti ti se.'],
localNotice: ['Preview mode: requests are not sent from this local site. Download your request to keep a copy. Uploads stay on your device and must be shared separately.','Vorschaumodus: Von dieser lokalen Website werden keine Anfragen gesendet. Lade deine Anfrage herunter. Dateien bleiben auf deinem Gerät und müssen separat geteilt werden.','Način pregleda: s ove lokalne stranice zahtjevi se ne šalju. Preuzmi svoj zahtjev. Datoteke ostaju na tvom uređaju i moraju se podijeliti zasebno.'], download: ['Download request','Anfrage herunterladen','Preuzmi zahtjev'], failure: ['Your request could not be sent. Please try again or download a copy.','Deine Anfrage konnte nicht gesendet werden. Versuche es erneut oder lade eine Kopie herunter.','Zahtjev nije poslan. Pokušaj ponovno ili preuzmi kopiju.'],
validationLang: ['Please select no more than 2 languages for the Simple Site package, or choose a Complex Website.','Bitte wähle höchstens 2 Sprachen für das einfache Paket oder eine komplexe Website.','Odaberi najviše 2 jezika za jednostavni paket ili odaberi složenu stranicu.'], fileError: ['Use PNG, JPG, WebP or GIF files: max. 20 files, 5 MB each, 8 MB combined.','Nutze PNG, JPG, WebP oder GIF: max. 20 Dateien, 5 MB je Datei, 8 MB insgesamt.','Koristi PNG, JPG, WebP ili GIF: najviše 20 datoteka, 5 MB po datoteci, ukupno 8 MB.'], urlsError: ['Enter complete http:// or https:// URLs, one per line.','Vollständige http://- oder https://-URLs eingeben, eine pro Zeile.','Unesi potpune http:// ili https:// URL-ove, jedan po retku.'], saved: ['Your request file is ready. It has not been sent.','Deine Anfrage-Datei ist bereit. Sie wurde nicht gesendet.','Datoteka zahtjeva je spremna. Nije poslana.'], required: ['* Required fields','* Pflichtfelder','* Obavezna polja']
};
export function translator(lang) { const i = Math.max(0, languages.indexOf(lang)); return key => { if (!copy[key]) throw new Error(`Missing translation: ${key}`); return copy[key][i]; }; }
export const projects = [
 {name:'Indigo',url:'https://filip-zafran.github.io/indigo/',style:'indigo',mark:'indigo.',description:['A simple business website','Eine einfache Unternehmenswebsite','Jednostavna poslovna stranica']},
 {name:'Antonio Alač Fitness',url:'https://filip-zafran.github.io/antonio-alac-fitness/',style:'fitness',mark:'ANTONIO ALAČ',description:['A personal fitness website','Eine persönliche Fitness-Website','Osobna fitness stranica']},
 {name:'Simona Eschweiler',url:'https://simona-eschweiler.vercel.app/',style:'simona',mark:'Simona Eschweiler',description:['A personal website','Eine persönliche Website','Osobna web stranica']},
 {name:'Ficho Films',url:'https://ficho-films.netlify.app/',style:'films',mark:'FICHO FILMS'},
 {name:'Duck Dating Apps',url:'https://duckdatingapps.com',style:'duck',mark:'Duck Dating Apps'},
 {name:'Poly Speed Dating',url:'https://poly-speed-dating.onrender.com/',style:'poly',mark:'Poly Speed Dating'},
 {name:'Berlin ↔ Zagreb',url:'https://berlin-zagreb.vercel.app/',style:'berlin',mark:'BERLIN ↔ ZAGREB'}
];
