// Template copy: replace bracketed fields in each language before using as final legal pages.
const text = {
 privacyTitle:['Privacy policy','Datenschutzerklärung','Politika privatnosti'],
 imprintTitle:['Legal notice','Impressum','Pravni podaci'],
 template:['Template — details to be completed','Vorlage — Angaben noch ergänzen','Predložak — potrebno je dopuniti podatke'],
 notice:['This page is a template. Bracketed fields must be completed for the actual operator, hosting and data processing before this becomes a final notice.','Diese Seite ist eine Vorlage. Angaben in Klammern müssen für den tatsächlichen Betreiber, das Hosting und die Datenverarbeitung ergänzt werden, bevor sie als endgültige Erklärung verwendet wird.','Ova je stranica predložak. Podatke u zagradama treba dopuniti za stvarnog vlasnika, hosting i obradu podataka prije korištenja kao konačne obavijesti.'],
 updated:['Last updated: [date]','Stand: [Datum]','Zadnje ažuriranje: [datum]'],
 privacyIntro:['How personal information is handled when you visit this website or submit a website request.','Wie personenbezogene Daten beim Besuch dieser Website und bei Website-Anfragen verarbeitet werden.','Kako se osobni podaci obrađuju prilikom posjeta ovoj stranici ili slanja zahtjeva za izradu stranice.'],
 imprintIntro:['Information about the operator of I Build Cheap Simple Websites Fast.','Angaben zum Betreiber von I Build Cheap Simple Websites Fast.','Podaci o vlasniku stranice I Build Cheap Simple Websites Fast.'],
 sources:['Reference sources','Referenzquellen','Referentni izvori']
};
const privacy = [
 [['Controller and contact','Verantwortlicher und Kontakt','Voditelj obrade i kontakt'],['[Full legal name / business name]\n[Postal address and country]\n[Email and other contact details]\n[Data protection officer contact, if applicable]','[Vollständiger Name / Unternehmensname]\n[Postanschrift und Land]\n[E-Mail und weitere Kontaktdaten]\n[Kontakt des Datenschutzbeauftragten, falls zutreffend]','[Puno ime / naziv tvrtke]\n[Poštanska adresa i država]\n[E-mail i ostali kontaktni podaci]\n[Kontakt službenika za zaštitu podataka, ako je primjenjivo]']],
 [['Hosting and server logs','Hosting und Serverprotokolle','Hosting i poslužiteljski zapisi'],['[Hosting provider, address and privacy-policy link]\n[Data recorded when visiting, purposes, legal basis and log retention period]\n[Recipients, processing locations and any international-transfer safeguards]','[Hosting-Anbieter, Anschrift und Link zur Datenschutzerklärung]\n[Beim Besuch erfasste Daten, Zwecke, Rechtsgrundlage und Speicherdauer der Protokolle]\n[Empfänger, Verarbeitungsorte und gegebenenfalls Garantien für Drittlandübermittlungen]','[Pružatelj hostinga, adresa i poveznica na politiku privatnosti]\n[Podaci zabilježeni pri posjetu, svrhe, pravna osnova i rok čuvanja zapisa]\n[Primatelji, mjesta obrade i zaštitne mjere za međunarodne prijenose]']],
 [['Website requests and uploaded files','Website-Anfragen und hochgeladene Dateien','Zahtjevi i učitane datoteke'],['The request form collects the contact details, project information, page content and files you choose to provide. These are intended for reviewing and responding to your project enquiry.\n[Confirm the processing purpose and legal basis; explain required and optional data and consequences of not providing it]\n[Actual form provider, recipients and processing locations]\n[Retention period or criteria and deletion process]','Das Anfrageformular erfasst die von dir angegebenen Kontaktdaten, Projektinformationen, Seiteninhalte und Dateien. Diese dienen dazu, deine Projektanfrage zu prüfen und zu beantworten.\n[Verarbeitungszweck und Rechtsgrundlage bestätigen; Pflichtangaben, freiwillige Angaben und Folgen einer Nichtbereitstellung erläutern]\n[Tatsächlicher Formularanbieter, Empfänger und Verarbeitungsorte]\n[Speicherdauer oder Kriterien und Löschverfahren]','Obrazac prikuplja kontaktne podatke, informacije o projektu, sadržaj stranica i datoteke koje odlučiš podijeliti. Namijenjeni su pregledu i odgovoru na tvoj upit.\n[Potvrdi svrhu i pravnu osnovu; objasni obavezne i neobavezne podatke te posljedice ako se ne pruže]\n[Stvarni pružatelj obrasca, primatelji i mjesta obrade]\n[Rok ili kriteriji čuvanja i postupak brisanja]']],
 [['Cookies, analytics and external services','Cookies, Analyse und externe Dienste','Kolačići, analitika i vanjske usluge'],['[List the cookies, browser storage, analytics and embedded services actually used, or state that none are used after verifying the live configuration]\n[Explain purposes, providers, storage duration and consent controls where applicable]\n[Describe any external services added to the deployed website]','[Tatsächlich verwendete Cookies, Browserspeicher, Analyse- und eingebettete Dienste auflisten oder nach Prüfung der Live-Konfiguration angeben, dass keine verwendet werden]\n[Zwecke, Anbieter, Speicherdauer und gegebenenfalls Einwilligungsmöglichkeiten erläutern]\n[Der veröffentlichten Website hinzugefügte externe Dienste beschreiben]','[Navedi stvarno korištene kolačiće, pohranu preglednika, analitiku i ugrađene usluge ili nakon provjere objavljene stranice navedi da se ne koriste]\n[Objasni svrhe, pružatelje, trajanje pohrane i upravljanje privolom gdje je primjenjivo]\n[Opiši vanjske usluge dodane na objavljenu stranicu]']],
 [['Your rights','Deine Rechte','Tvoja prava'],['Depending on the applicable conditions, you may request access, correction, erasure, restriction or portability of your personal data and object to processing. Where processing relies on consent, you may withdraw that consent for the future. You may also complain to a competent supervisory authority.\n[Contact for exercising rights]\n[Competent supervisory authority and contact or link]','Unter den jeweiligen Voraussetzungen kannst du Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragbarkeit deiner personenbezogenen Daten verlangen und der Verarbeitung widersprechen. Soweit die Verarbeitung auf einer Einwilligung beruht, kannst du diese für die Zukunft widerrufen. Du kannst dich außerdem bei einer zuständigen Aufsichtsbehörde beschweren.\n[Kontakt zur Ausübung der Rechte]\n[Zuständige Aufsichtsbehörde mit Kontakt oder Link]','Pod primjenjivim uvjetima možeš zatražiti pristup, ispravak, brisanje, ograničenje ili prenosivost osobnih podataka te prigovoriti obradi. Ako se obrada temelji na privoli, možeš je povući za buduću obradu. Možeš podnijeti i pritužbu nadležnom nadzornom tijelu.\n[Kontakt za ostvarivanje prava]\n[Nadležno nadzorno tijelo i kontakt ili poveznica]']],
 [['Additional processing details','Weitere Angaben zur Verarbeitung','Dodatni podaci o obradi'],['[Describe any automated decision-making or profiling, or confirm that none occurs]\n[Describe any other processing purposes, legal bases, recipients and retention periods]\n[Update this notice when the actual website services change]','[Automatisierte Entscheidungen oder Profiling beschreiben oder bestätigen, dass diese nicht stattfinden]\n[Weitere Verarbeitungszwecke, Rechtsgrundlagen, Empfänger und Speicherfristen beschreiben]\n[Diese Erklärung bei Änderungen der tatsächlichen Website-Dienste aktualisieren]','[Opiši automatizirano odlučivanje ili profiliranje ili potvrdi da se ne provodi]\n[Opiši ostale svrhe obrade, pravne osnove, primatelje i rokove čuvanja]\n[Ažuriraj ovu obavijest pri promjenama stvarnih usluga stranice]']]
];
const imprint = [
 [['Website operator','Website-Betreiber','Vlasnik stranice'],['[Full legal name / company name]\n[Legal form, if applicable]\n[Street and house number]\n[Postal code, city and country]\n[Authorised representative, if applicable]','[Vollständiger Name / Unternehmensname]\n[Rechtsform, falls zutreffend]\n[Straße und Hausnummer]\n[Postleitzahl, Ort und Land]\n[Vertretungsberechtigte Person, falls zutreffend]','[Puno ime / naziv tvrtke]\n[Pravni oblik, ako je primjenjivo]\n[Ulica i kućni broj]\n[Poštanski broj, grad i država]\n[Ovlašteni zastupnik, ako je primjenjivo]']],
 [['Contact','Kontakt','Kontakt'],['[Email address]\n[Phone number or other direct communication channel]','[E-Mail-Adresse]\n[Telefonnummer oder anderer unmittelbarer Kommunikationsweg]','[E-mail adresa]\n[Broj telefona ili drugi kanal izravne komunikacije]']],
 [['Registration and identification','Register und Identifikation','Registracija i identifikacija'],['[Register and registration number, if applicable]\n[VAT identification or business identification number, if applicable]','[Register und Registernummer, falls zutreffend]\n[Umsatzsteuer- oder Wirtschafts-Identifikationsnummer, falls zutreffend]','[Registar i registracijski broj, ako je primjenjivo]\n[PDV identifikacijski ili poslovni identifikacijski broj, ako je primjenjivo]']],
 [['Additional applicable information','Weitere zutreffende Angaben','Dodatni primjenjivi podaci'],['[Supervisory authority for activities requiring authorisation, if applicable]\n[Professional title, chamber, applicable professional rules and how to access them, if applicable]\n[Other disclosures applicable to the operator and service; remove irrelevant placeholders]','[Aufsichtsbehörde bei zulassungspflichtiger Tätigkeit, falls zutreffend]\n[Berufsbezeichnung, Kammer, berufsrechtliche Regelungen und Zugang dazu, falls zutreffend]\n[Weitere für Betreiber und Dienst zutreffende Angaben; nicht relevante Platzhalter entfernen]','[Nadzorno tijelo za djelatnosti koje zahtijevaju odobrenje, ako je primjenjivo]\n[Stručni naziv, komora, strukovna pravila i pristup njima, ako je primjenjivo]\n[Ostale objave primjenjive na vlasnika i uslugu; ukloni nevažne oznake mjesta]']]
];
export const legalRoutes=['datenschutz','impressum'];
export function legalTitle(route,lang){return text[route==='datenschutz'?'privacyTitle':'imprintTitle'][['en','de','hr'].indexOf(lang)]}
export function renderLegal(route,lang){
 const i=['en','de','hr'].indexOf(lang),t=key=>text[key][i],sections=route==='datenschutz'?privacy:imprint;
 return `<article class="container page-hero legal-page"><p class="eyebrow">${t('template')}</p><h1>${legalTitle(route,lang)}</h1><p class="hero-description">${t(route==='datenschutz'?'privacyIntro':'imprintIntro')}</p><p class="notice">${t('notice')}</p><p class="hint">${t('updated')}</p>${sections.map(([heading,body])=>`<section><h2>${heading[i]}</h2>${body[i].split('\n').map(line=>`<p>${line}</p>`).join('')}</section>`).join('')}<div class="legal-sources"><h2>${t('sources')}</h2><a href="https://www.gesetze-im-internet.de/ddg/__5.html" target="_blank" rel="noopener noreferrer">§ 5 DDG ↗</a> · <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" target="_blank" rel="noopener noreferrer">${['GDPR','DSGVO','Opća uredba o zaštiti podataka'][i]} ↗</a></div></article>`;
}
